name: Build CV PDFs

on:
  push:
    branches: [ main, Jurado-Distri ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TeX Live (XeLaTeX)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-xetex \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            latexmk \
            fonts-dejavu fonts-freefont-ttf

      - name: Build both PDFs via Makefile
        run: make both

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdfs
          path: |
            cv_english.pdf
            cv_spanish.pdf

