name: Build and Release CV

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-cv:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Compile both CV versions
      uses: xu-cheng/texlive-action@v3
      with:
        os: debian
        scheme: full
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -y
          apt-get install -y make
          make both
        
    - name: Upload CV files to GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.event.release.tag_name }} \
          cv_spanish.pdf \
          cv_english.pdf \
          --clobber